language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c "create user connie with password 'connie';" -U postgres
  - psql -c 'create database connie_test owner connie;' -U postgres
  - rake db:test:prepare